layout_spectrum: 0.6099348720163107
typography_spectrum: 0.10076412023045123
color:
  brandStrength: 0.7585384824778885
  lightness: 0.3175355272833258
  saturation: 0.37195986532606184
  rhythmicContrast: 0.31417158897966146
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: KV Photos
navigation:
  - name: Hot Colors for fashion
    url: 'http://www.pantone.com/color-of-the-year-2016?from=topNav'
    type: external
